# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: About
    url: /#about
    weight: 20
  - name: Topics
    url: /#topics
    weight: 30
  - name: Speakers
    url: /#speakers
    weight: 40
  - name: Coordinators
    url: /#coordinators
    weight: 50
  - name: Venue
    url: /#venue
    weight: 60
  - name: Contact
    url: /#contact
    weight: 70