# config/_default/menus.yaml - Updated

main:
  - name: Home
    url: /#top
    weight: 10
  - name: About
    url: /#about
    weight: 20
  - name: Topics
    url: /#topics
    weight: 30
  - name: Speakers
    url: /#speakers
    weight: 40
  - name: Program
    url: /#program
    weight: 50
  - name: Venue
    url: /#venue
    weight: 60
  - name: Contact
    url: /#contacts
    weight: 70
  - name: Sponsors
    url: /#sponsors
    weight: 80
