# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: green

# SEO
marketing:
  icon:
    filename: 'iisc-logo.png'
    # Specify the image files directly if you have them, or keep them pointing to the main file:
    favicon: 'iisc-logo.png' 
    apple_touch_icon: 'iisc-logo.png'
  seo:
    site_type: Event
    local_business_type: ''
    org_name: 'Indian Institute of Science, Bengaluru'
    description: 'ACM India Winter School 2025 on Edge AI Hosted by Indian Institute of Science, Bengaluru (28 DECEMBER 2025 - 4 JANUARY 2026)'
    twitter: '' # Add official X handle if available
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    align: 'center'
    fixed_to_top: true
    logo:
      text: '' # Winter School on Edge AI
      # Logo filename in `assets/media/` folder
      filename: 'IISC.svg' # Remove default logo or add one like 'iisc-logo.svg'
    show_search: false
    show_theme_chooser: false
    favicon: 'iisc-logo.png'

styles:
  css:
    - css/custom.css   

# Site footer
footer:
  copyright:
    notice: 'Â© {year} ACM India Winter School. Hosted by IISc.'

# Localization
locale:
  date_format: '11 Nov 2025' # Use a clearer date format
  time_format: '11:18 AM'
