# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Event
    local_business_type: ''
    org_name: 'Indian Institute of Science, Bengaluru'
    description: 'ACM India Winter School 2025 on Edge AI Hosted by Indian Institute of Science, Bengaluru (28 DECEMBER 2025 - 4 JANUARY 2026)'
    twitter: '' # Add official X handle if available
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    align: 'center'
    fixed_to_top: true
    logo:
      text: 'Edge AI Winter School' # Main text logo
      # Logo filename in `assets/media/` folder
      filename: '' # Remove default logo or add one like 'iisc-logo.svg'
    button:
      enable: true
      text: 'Apply Now' # Action button
      url: '#contact' # Link to the Contact section (or an external application link)
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: 'Â© {year} ACM India Winter School. Hosted by IISc.'

# Localization
locale:
  date_format: '2 Jan 2006' # Use a clearer date format
  time_format: '3:04 PM'